module.exports = {
	playWhileRunning: 'PlayWhileRunning',
	startOnFaderUp: 'StartOnFaderUp',
	releaseOnFaderDown: 'ReleaseOnFaderDown',
	speedMaster: 'SpeedMaster',
	fxSpeedMaster: 'FxSpeedMaster',
	extraSubmaster: 'ExtraSubMaster',
	releaseTime: 'ReleaseTime',
	autoReleaseOnEnd: 'AutoReleaseOnEnd',
	useHtp: 'UseHTP',
	smooth: 'Smooth',
	priority: 'Priority',
	trackingMode: 'TrackingMode',
	trackingNotInJumps: 'TrackingNotInJumps',
	masterInfluenceAutomatic: 'MasterInfluenceAutomatic',
	masterInfluenceIntensity: 'MasterInfluenceIntensity',
	masterInfluenceFocus: 'MasterInfluenceFocus',
	masterInfluenceColor: 'MasterInfluenceColor',
	masterInfluenceBeam: 'MasterInfluenceBeam',
	mutualExcludeGroup: 'MutualExcludeGroup',
	protectedGroup: 'ProtectedGroup',
	chaserType: 'ChaserType',
	chaserSpeed: 'ChaserSpeed',
	chaserCrossfade: 'ChaserCrossfade',
	bmpTeachIn: 'BPMTeachIn',
	chaserSpeedFromAudioDsp: 'ChaserSpeedFromAudioDsp',
}